# Name of your application. Used to uniquely configure containers.
service: monitool

# Name of the container image.
image: t-gitt/monitool

# volumes:
#   - data:/app/data

# Deploy to these servers.
servers:
  web:
    hosts:
      - monitool.turnrow.online

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption. 
proxy: 
  app_port: 80
  ssl: true
  hosts:
    - monitool.turnrow.online


# Configure builder setup.
builder:
  arch: arm64
  context: ./frontend
  dockerfile: ./frontend/Dockerfile
  args:
    VITE_API_URL: https://be-monitool.turnrow.online
    VITE_API_KEY: "as12388kdjalsur12o12nr;3mt1"

